services:
  - type: web
    name: digit-recognition-api
    env: python
    buildCommand: pip install -e .
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0